# Created with podman-5.2.5
# Create Pod and PersistentVolumeClaim for HamClock
apiVersion: v1
kind: Pod
metadata:
  labels:
    app: hamclock-pod
  name: hamclock-pod
spec:
  containers:
  - image: localhost/hamclock:latest
    name: hamclock
    env:
      # PLEASE COPY THIS FILE TO config.env
    - name: CALLSIGN
      value: AB1CDE
      # Use 6-digit locator
    - name: LOCATOR
      value: AA00aa
      # Positive numbers are north, negative south
    - name: LAT
      value: "40.00"
      # Positive numbers are east, negative west
    - name: LONG
      value: "-70.00"
      # UTC offset in hours. Negative number for negative offset
    - name: UTC_OFFSET
      value: "-4"
      # CW=19 SSB=38 AM=49 WSPR=3 FT8=13 FT4=17
    - name: VOACAP_MODE
      value: "38"
      # Power in Watts
    - name: VOACAP_POWER
      value: "10"
      # RGB Values
    - name: CALLSIGN_BACKGROUND_COLOR
      value: "80,80,80"
      # Set to 1 if you want to have the rainbow. Overwrites color setting from above
    - name: CALLSIGN_BACKGROUND_RAINBOW
      value: "100,100,100"
      # RGB Values
    - name: CALLSIGN_COLOR
      value: "10,10,10"
      # Portnumber of FLRIG
    - name: FLRIG_PORT
      value: "12345"
      # Hostname or IP of FLRIG
    - name: FLRIG_HOST
      value: "localhost"
      # 1=Use FLRIG, 0=Don't use FLRIG
    - name: USE_FLRIG
      value: "0"
      # 1=Use Metric System 0=Don't use it
    - name: USE_METRIC
      value: "1"
      # WIFI Settings
    - name: WIFI_SSID
      value: "no-SSID"
    - name: WIFI_PWD
      value: "no-PWD"
    - name: SHOW_PUB_IP
      value: "1"
    # Expose the following ports
    ports:
    # system settings port (probably should only be exposed on localhost)
    - containerPort: 8080
      hostPort: 8080
    # hamclock web interface R/W (Probably should NOT be exposed to the world)
    - containerPort: 8081
      hostPort: 8081
    # hamclock web interface R/O (Probably should be exposed to the world if you're sharing your hamclock)
    - containerPort: 8082
      hostPort: 8082
    stdin: true
    tty: true
    # Limit the resources the container can use
    resources:
      limits:
        memory: "128Mi"
        cpu: "500m"
      requests:
        memory: "64Mi"
        cpu: "250m"
    restartPolicy: unless-stopped
    # Liveness probe to check if the container is still alive
    livenessProbe:
      httpGet:
        path: /get_sys.txt
        port: 8080
      initialDelaySeconds: 120
      periodSeconds: 30
      timeoutSeconds: 10
      failureThreshold: 3
    volumeMounts:
    - mountPath: /root/.hamclock
      name: hamclock-pvc
  volumes:
  - name: hamclock-pvc
    persistentVolumeClaim:
      claimName: hamclock-volume
---
# Persistent storage for hamclock
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: hamclock-volume
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 64Mi